#Mayhem Tactical
!Mayhem Tactical
#Continuous floodgates
82732705 0 --Skill Drain
24207889 0 --There Can Be Only One
53334471 0 --Gozen Match
90846359 0 --Rivalry of Warlords
58921041 0 --Anti-Spell Fragrance
81674782 0 --Dimensional Fissure
30241314 0 --Macro Cosmos
#Lingering turn locks
94145021 0 --Droll & Lock Bird
94145022 0 --Droll & Lock Bird
20292186 0 --Artifact Scythe
15939229 0 --D/D/D Duo-Dawn King Kali Yuga
62242678 0 --Hot Red Dragon Archfiend King Calamity
