"""Resolve the neutral Token used by mutation cores from the client's cards.cdb."""

from __future__ import annotations

import sqlite3
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TOKEN_NAME = "Koa'ki Meiru Token"
OUTPUT = REPO / "src" / "runtime" / "mayhem_token_codes.lua"


def main() -> int:
    remembered = REPO / ".game-path"
    text = remembered.read_text(encoding="utf-8").strip() if remembered.is_file() else ""
    if not text:
        raise SystemExit("No EDOPro folder known. Run tools/install.ps1 first.")
    game = Path(text)
    ids: set[int] = set()
    for database in sorted((game / "expansions").glob("*.cdb")):
        connection = sqlite3.connect(f"file:{database.as_posix()}?mode=ro", uri=True)
        try:
            ids.update(row[0] for row in connection.execute(
                "SELECT id FROM texts WHERE name = ?", (TOKEN_NAME,)
            ))
        finally:
            connection.close()
    ids = sorted(ids)
    if len(ids) != 1:
        raise SystemExit(f"expected exactly one '{TOKEN_NAME}', found {ids}")
    OUTPUT.write_text(
        "-- Generated by tools/build-token-codes.py; do not edit by hand.\n"
        f"MAYHEM_TOKEN_CODE = {ids[0]}\n",
        encoding="utf-8",
    )
    print(f"resolved {TOKEN_NAME}: {ids[0]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
